<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Crowbar.Editor</AssemblyName>
    <RootNamespace>Crowbar.Editor</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Engine\Engine.csproj" />
    <None Include="Ui\**\*.razor" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Ui\**\*.css" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
