using System.Reflection;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.AspNetCore.Razor.Language.Intermediate;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Crowbar.UI;

/// <summary>
/// Compiles Razor templates into <see cref="RazorPanel"/> components at runtime.
///
/// The compiler leans on the Razor language API as much as possible instead of
/// re-parsing the source with regular expressions:
/// <list type="bullet">
/// <item>the project engine runs in the legacy file kind, where the core
/// directives (<c>@inherits</c>, <c>@implements</c>, <c>@using</c>,
/// <c>@namespace</c>, <c>@functions</c>) are native;</item>
/// <item><c>@code</c> blocks are aliased to the native <c>@functions</c>
/// directive so class members are generated by Razor itself;</item>
/// <item>a <see cref="DirectiveCapturePass"/> reads every directive back from
/// the intermediate document (routes, base type, interfaces, namespace)
/// before the classifier passes consume them;</item>
/// <item><c>@page</c> is registered for the legacy file kind so routes parse
/// cleanly; the generated output carries no trace of it, since routes are
/// consumed by <see cref="UiSystem"/>.</item>
/// </list>
/// </summary>
public sealed class RazorComponentFactory(IReadOnlyDictionary<string, Func<RazorPanel>>? components = null)
    : IRazorComponentCompiler
{
    private readonly IReadOnlyDictionary<string, Func<RazorPanel>> _components =
        components ?? new Dictionary<string, Func<RazorPanel>>(StringComparer.OrdinalIgnoreCase);

    public PanelComponent Compile(string razorSource, string className, Type baseType, params Assembly[] references)
    {
        var template = CompileTemplate(razorSource, className, baseType, references);
        return BuildTree(template);
    }

    public RazorPanel CompileTemplate(string razorSource, string className, Type baseType, params Assembly[] references)
    {
        var assembly = CompileAssembly(razorSource, className, baseType, references);
        return CreateTemplate(assembly, className);
    }

    /// <summary>
    /// Compiles the component from a file, caching the emitted assembly by
    /// (path, className, write time) so hot reloads of unchanged files skip the
    /// Roslyn emit. A fresh template instance is created on every call.
    /// </summary>
    public RazorPanel CompileTemplateFromFile(string razorPath, string className, Type baseType,
        params Assembly[] references)
    {
        razorPath = Path.GetFullPath(razorPath);
        var writeTime = File.GetLastWriteTimeUtc(razorPath).Ticks;
        var cacheKey = razorPath + "|" + className + "|" + (baseType.FullName ?? baseType.Name);
        var assembly = TemplateAssemblyCache.Get(cacheKey, writeTime);
        if (assembly is null)
        {
            assembly = CompileAssembly(ReadStableFileText(razorPath), className, baseType, references);
            TemplateAssemblyCache.Set(cacheKey, writeTime, assembly);
        }

        return CreateTemplate(assembly, className);
    }

    private static Assembly CompileAssembly(string razorSource, string className, Type baseType,
        params Assembly[] references)
    {
        // Event and binding expressions are intentionally converted to stable
        // markers before Razor parses the document. This keeps the generated
        // class strongly typed for @code, @if, @foreach and expressions while
        // allowing the native Panel tree to attach delegates after rendering.
        var source = RewriteCodeToFunctions(RewriteUiAttributes(razorSource));

        var engine = CreateProjectEngine();
        var directives = ParseDirectives(source, engine, className);
        ValidateBaseType(directives.BaseTypeName, baseType, references, directives.Usings);

        // The legacy document classifier does not apply @namespace itself, so
        // the captured directive value is fed to SetNamespace of the engine
        // used for the actual generation.
        var document = RazorSourceDocument.Create(source, className + ".razor");
        var generationEngine = CreateProjectEngine(directives.NamespaceName);
        var codeDocument = generationEngine.Process(document, fileKind: null, [], []);
        var generatedCode = codeDocument.GetCSharpDocument().GeneratedCode;
        var defaultUsings = new[]
        {
            "System",
            "System.Collections.Generic",
            "System.Linq",
            "System.Threading",
            "System.Threading.Tasks"
        };
        generatedCode = string.Join(Environment.NewLine, defaultUsings.Select(u => $"using {u};")) +
                        Environment.NewLine + generatedCode;

        var tree = CSharpSyntaxTree.ParseText(generatedCode);
        var platformReferences = ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") ?? string.Empty)
            .Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries)
            .Select(path => MetadataReference.CreateFromFile(path));
        var assemblyReferences = references.Concat([
                typeof(object).Assembly, typeof(Enumerable).Assembly,
                typeof(RazorPanel).Assembly, typeof(RazorProjectEngine).Assembly
            ])
            .Distinct().Select(a => MetadataReference.CreateFromFile(a.Location)).Concat(platformReferences);
        var compilation = CSharpCompilation.Create(
            "Crowbar.UI.Razor." + Guid.NewGuid().ToString("N"), [tree], assemblyReferences,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        using var stream = new MemoryStream();
        var result = compilation.Emit(stream);
        if (!result.Success)
            throw new InvalidOperationException("Razor compilation failed:\n" + string.Join('\n',
                result.Diagnostics.Where(d => d.Severity == DiagnosticSeverity.Error)));
        stream.Position = 0;
        return Assembly.Load(stream.ToArray());
    }

    private static RazorPanel CreateTemplate(Assembly assembly, string className)
    {
        var generatedType = assembly.GetTypes()
                                .FirstOrDefault(t => t.Name.Equals(className, StringComparison.OrdinalIgnoreCase))
                            ?? assembly.GetTypes().FirstOrDefault(t => typeof(RazorPanel).IsAssignableFrom(t));
        if (generatedType is null)
            throw new InvalidOperationException("Razor output did not contain a component type.");
        var templateInstance = (RazorPanel)Activator.CreateInstance(generatedType)!;
        if (string.IsNullOrEmpty(templateInstance.ScopeId))
            templateInstance.ScopeId = $"b-{className.ToLowerInvariant()}";
        return templateInstance;
    }

    private static string ReadStableFileText(string path)
    {
        string? previous = null;
        for (var attempt = 0; attempt < 6; attempt++)
        {
            try
            {
                using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
                using var reader = new StreamReader(stream);
                var text = reader.ReadToEnd();
                if (previous is not null && previous == text) return text;
                previous = text;
                Thread.Sleep(30);
            }
            catch (IOException) when (attempt < 3)
            {
                Thread.Sleep(25);
            }
        }

        return previous ?? File.ReadAllText(path);
    }

    private static readonly TemplateAssemblyCacheStore TemplateAssemblyCache = new();

    private sealed class TemplateAssemblyCacheStore
    {
        private const int MaxEntries = 32;

        private readonly Dictionary<string, (long WriteTime, Assembly Assembly, long LastUse)> _entries =
            new(StringComparer.Ordinal);

        private readonly object _lock = new();

        public Assembly? Get(string key, long writeTime)
        {
            lock (_lock)
            {
                if (_entries.TryGetValue(key, out var entry) && entry.WriteTime == writeTime)
                {
                    _entries[key] = (entry.WriteTime, entry.Assembly, Environment.TickCount64);
                    return entry.Assembly;
                }
            }

            return null;
        }

        public void Set(string key, long writeTime, Assembly assembly)
        {
            lock (_lock)
            {
                _entries[key] = (writeTime, assembly, Environment.TickCount64);
                if (_entries.Count <= MaxEntries) return;
                foreach (var stale in _entries.OrderBy(kv => kv.Value.LastUse).Take(_entries.Count - MaxEntries))
                    _entries.Remove(stale.Key);
            }
        }
    }

    public PanelComponent BuildTree(RazorPanel template)
    {
        if (!template.NeedsBuild() && !template.NeedsContentRebuild()) return template;
        if (!template.CanRender())
        {
            template.MarkRenderSkipped();
            return template;
        }

        template.BeginRenderPass();
        var markup = template.RenderMarkupAsync().GetAwaiter().GetResult();
        var root = HtmlPanelParser.Parse(markup, template, _components);
        template.EndRenderPass();
        var firstRender = template.MarkBuilt(null);
        template.MarkChildContentBuilt();
        template.NotifyRendered(firstRender);
        return root;
    }

    private static string RewriteUiAttributes(string source)
    {
        source = RewriteAttribute(source, "@onclick", "data-codex-onclick");
        source = RewriteAttribute(source, "@onchange", "data-codex-onchange");
        source = RewriteAttribute(source, "@bind-value", "data-codex-bind-value");
        source = RewriteAttribute(source, "@bind", "data-codex-bind-value");
        return source;
    }

    private static string RewriteAttribute(string source, string attributeName, string targetName)
    {
        var pattern = $@"{Regex.Escape(attributeName)}\s*=\s*(?:(['""])([^'""]+)\1|([^\s>]+))";
        return Regex.Replace(source, pattern, m =>
        {
            var val = (m.Groups[2].Success ? m.Groups[2].Value : m.Groups[3].Value).Trim();
            val = CleanRazorExpression(val);
            return $"{targetName}=\"{val}\"";
        }, RegexOptions.IgnoreCase);
    }

    internal static string CleanRazorExpression(string val)
    {
        val = val.Trim();
        if (val.StartsWith("@", StringComparison.Ordinal))
        {
            val = val[1..].Trim();
            if (val.StartsWith("(", StringComparison.Ordinal) && val.EndsWith(")", StringComparison.Ordinal))
            {
                val = val[1..^1].Trim();
            }
        }

        return val;
    }

    // ---- Razor directive handling -------------------------------------------------

    /// <summary>Returns the route templates declared by <c>@page</c> directives in a Razor source.</summary>
    public static string[] ExtractPages(string source) =>
        ParseDirectives(RewriteCodeToFunctions(source), CreateProjectEngine(), "pages").Pages.ToArray();

    private static RazorProjectEngine CreateProjectEngine(string? namespaceName = null)
    {
        return RazorProjectEngine.Create(RazorConfiguration.Default,
            RazorProjectFileSystem.Create(AppContext.BaseDirectory), b =>
            {
                b.SetNamespace(namespaceName ?? "Crowbar.UI.Generated");
                b.SetBaseType(typeof(RazorPanel).FullName!);
                // @page is a components-only directive; register it for the
                // legacy file kind so templates can declare routes. Its output
                // is consumed by UiSystem, never emitted.
                b.AddDirective(DirectiveDescriptor.CreateDirective("page", DirectiveKind.SingleLine,
                    d => d.AddStringToken()));
                // Captures every directive before the classifier passes consume
                // them, and stashes them on the code document.
                b.Features.Add(new DirectiveCapturePass());
            });
    }

    private static RazorDirectives ParseDirectives(string source, RazorProjectEngine engine, string fileName)
    {
        var document = RazorSourceDocument.Create(source, fileName);
        var codeDocument = engine.Process(document, fileKind: null, [], []);
        return (RazorDirectives)codeDocument.Items[DirectiveCapturePass.CaptureKey]!;
    }

    private static void ValidateBaseType(string? baseTypeName, Type fallback, Assembly[] references,
        IReadOnlyList<string> usings)
    {
        var effectiveBase = baseTypeName is null
            ? (typeof(RazorPanel).IsAssignableFrom(fallback) ? fallback : typeof(RazorPanel))
            : ResolveType(baseTypeName, references, "base type", usings);
        if (!typeof(RazorPanel).IsAssignableFrom(effectiveBase))
            throw new InvalidOperationException($"Razor base type '{effectiveBase.FullName}' must derive from RazorPanel.");
        if (effectiveBase.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null,
                Type.EmptyTypes, null) is null)
            throw new InvalidOperationException(
                $"Razor base type '{effectiveBase.FullName}' must have a parameterless constructor.");
    }

    private static Type ResolveType(string name, Assembly[] references, string kind, IReadOnlyList<string> usings)
    {
        var candidates = references.Concat(AppDomain.CurrentDomain.GetAssemblies()).Distinct();
        var names = new[] { name }.Concat(usings.Select(usingName => usingName + "." + name));
        var type = names
            .SelectMany(candidate => candidates.Select(assembly => assembly.GetType(candidate, false, false)))
            .FirstOrDefault(found => found is not null) ?? names
            .Select(candidate => Type.GetType(candidate, false, false)).FirstOrDefault(found => found is not null);
        return type ?? throw new InvalidOperationException($"Razor {kind} '{name}' could not be resolved.");
    }

    /// <summary>
    /// Aliases <c>@code</c> blocks to the native <c>@functions</c> directive.
    /// <c>@code</c> is a Razor Components directive that only exists in the
    /// component file kind; the legacy kind the runtime compiler uses ships the
    /// equivalent <c>@functions</c> natively.
    /// </summary>
    private static string RewriteCodeToFunctions(string source) =>
        Regex.Replace(source, @"(?m)^(\s*)@code(?=[\s{])", "$1@functions");
}

/// <summary>Directives extracted from a Razor source through the language API.</summary>
internal sealed record RazorDirectives(
    string? BaseTypeName,
    IReadOnlyList<string> Interfaces,
    IReadOnlyList<string> Usings,
    string? NamespaceName,
    IReadOnlyList<string> Pages);

/// <summary>
/// Runs first in the optimization phase and records every directive of the
/// document (routes, base type, interfaces, namespace and usings) before the
/// classifier passes consume or remove them. The captured values are stashed on
/// the code document so the compiler can read them back.
/// </summary>
internal sealed class DirectiveCapturePass : RazorEngineFeatureBase, IRazorOptimizationPass
{
    /// <summary>Key under which the captured <see cref="RazorDirectives"/> are stored on the code document.</summary>
    public static readonly object CaptureKey = new();

    public int Order => int.MinValue;

    public void Execute(RazorCodeDocument codeDocument, DocumentIntermediateNode documentNode)
    {
        var pages = new List<string>();
        string? baseTypeName = null;
        var interfaces = new List<string>();
        var usings = new List<string>();
        string? namespaceName = null;
        Walk(documentNode);

        codeDocument.Items[CaptureKey] = new RazorDirectives(baseTypeName, interfaces, usings, namespaceName, pages);
        return;

        void Walk(IntermediateNode node)
        {
            switch (node)
            {
                case DirectiveIntermediateNode directive:
                    var tokens = directive.Tokens.Select(t => t.Content).ToArray();
                    switch (directive.Directive.Directive)
                    {
                        case "page":
                            pages.AddRange(tokens.Select(t => t.Trim().Trim('"')));
                            break;
                        case "inherits":
                            baseTypeName = tokens.FirstOrDefault();
                            break;
                        case "implements":
                            interfaces.AddRange(tokens);
                            break;
                        case "namespace":
                            namespaceName = tokens.FirstOrDefault();
                            break;
                    }

                    break;
                case UsingDirectiveIntermediateNode usingDirective:
                    usings.Add(usingDirective.Content);
                    break;
            }

            foreach (var child in node.Children) Walk(child);
        }
    }
}
